### ISSUE TITLE
HEAD node Rx deadlock

### ISSUE THREAD

**Issue by hecmay** [ngdxzy/OCT_FPGA_Project_Template_for_Nextlab#2]
Hi, 

I am trying a simplified version with two FPGAs to realize the loopback: it is basically the HEAD node + TAIL node (as I cannot reserve more than 2 FPGAs on OCT as of now)

Here is what I did. First, I compiled the bitstreams `bit_container_0.xclbin` for HEAD node and `bit_container_1.xclbin` for TAIL node using Vitis 2021.2 (along with other host binaries to set up IP address)

Second, I changed the INI configuration, connecting from HEAD(192.168.2.10:50000) to TAIL (192.168.2.20:60000)
```ini
# head_ip.ini
192.168.2.10
50000:192.168.2.20:60000
```

```ini
# tail_ip.ini
192.168.2.20
60000:192.168.2.10:50000
```

and Finally, I copied the files to OCT cloud nodes, and run the following commands

```bash
# Setup the HEAD node IP on node0@pc-155
sx233@node0:~$ ./udp_setup bit_container_0.xclbin head_ip.ini 
Using FPGA binary file specfied through the command line: bit_container_0.xclbin 
Setting up CMAC 0
Get user specified IP address: c0a8020a
Get 00th socket conncection 192.168.2.10:50000 <->  192.168.2.20:60000
Using gateway: c0a802ff
Using MAC: f1f2f3f40a
Loading bit_container_0.xclbin 
Device name:  xilinx_u280_xdma_201920_3
Device bdf:   0000:3b:00.1
There are 16 hardware sockets.
ARP valid entry found at 20
TX status 0
RX status 3
Link is as active!
```

Then set up the TAIL node IP on node1@pc-158
```bash
sx233@node1:~$ ./udp_setup bit_container_1.xclbin tail_ip.ini
Using FPGA binary file specfied through the command line: bit_container_1.xclbin 
Setting up CMAC 0
Get user specified IP address: c0a80214
Get 00th socket conncection 192.168.2.20:60000 <->  192.168.2.10:50000
Using gateway: c0a802ff
Using MAC: f1f2f3f414
Loading bit_container_1.xclbin 
Device name:  xilinx_u280_xdma_201920_3
Device bdf:   0000:3b:00.1
There are 16 hardware sockets.
ARP valid entry found at 10
TX status 0
RX status 3
Link is as active!

# and run `./tail_bin bit_container_1.xclbin ` to enable auto-data-pack (I suppose?)
sx233@node1:~$ ./tail_bin bit_container_1.xclbin 
Using FPGA binary file specfied through the command line: bit_container_1.xclbin 
Send 704 Bytes to Sokcet 0
All kernel finished!
```

In the very end, I go back to HEAD node to transmit data
```bash
sx233@node1:~$ ./head_bin bit_container_0.xclbin 704
Using FPGA binary file specfied through the command line: bit_container_0.xclbin 
Send 704 Bytes to Sokcet 0
File alice29.txt read!
All kernel started!
All kernel finished!
All kernel started!
All kernel finished!
************************************************











************************************************
```

It receives no data, and the CU kernel on node1's FPGA is deadlocked.

**Comment by hecmay** [comment]
Oh, I just figured out you need to set the IP address on HEAD node once again before you initiating data transmit request on it

```bash
$ ./udp_setup bit_container_0.xclbin head_ip.ini
$ ./head_bin bit_container_0.xclbin 1024
```

and it would work!

**Comment by ngdxzy** [comment]
Yes, it is tricky because we cannot set up all FPGAs simultaneously. When we set up FPGA1, the FPGA2 hasn't been set up so the ARP discovery FPGA1 cannot find FPGA2. Mostly, we have to run udp_setup at twice except for the last one...

**Comment by hecmay** [comment]
@ngdxzy thanks for the information. I also found that even if all the FPGAs are set up correctly, the FPGA on the HEAD node may still get deadlocked sometimes (due to packet loss or something I guess?)

I was able to run it successfully just now (for around ~1000 times to collect some latency data), and all of a sudden, it stopped working (i.e., the HEAD node cannot receive any data it has sent out and Rx kernel keeps waiting there)

**Comment by hecmay** [comment]
> I was able to run it successfully just now (for around ~1000 times to collect some latency data), and all of a sudden, it stopped working (i.e., the HEAD node cannot receive any data it has sent out and Rx kernel keeps waiting there)

Not so sure why. My hypothesis is that someone else in the cluster is using the same IP:PORT settings, so the packet was forwarded to their device. I ran into such scenarios when running the udp-demo example, where my receiver node receives some data before I started the sender node (so it must be the data from someone else)

but even if I changed the IP, it still does not work now. the only good thing is that at least it works sometimes

**Comment by ngdxzy** [comment]
@hecmay  Interesting. It is tricky as we cannot use hardware emulation to debug this. I encountered a similar problem with you. When I was setting the IP of the first FPGA1, I found the APR valid entry of FPGA2 and FPGA3 are already found (I haven't set them). My solution was to change the IP address (such as 192.168.3.10 or even more weird ones). Sometimes resetting the FPGA with 'xbutil reset -d ...' may help.

In addition, I write the received data into data_received.txt, you can check if it is a whole UDP packet that is lost or just several 64 Bytes Stream transitions are lost. For example, there was one time that I tried 1408+704 Bytes (1.5 UDP packet), but I only get the first 22 stream transitions (33 transitions expect). In this case, the second UDP packet is lost. In this case, it could be related to their Network setup. If 25 transitions are received (for example), then it could be the problem of my kernels that some stream transitions are lost.
